"""
constants.py

Defined constants.

Author: Chiao-Yu Wang (Student No. 48007506)
"""
IMAGE_SIZE = 128
BATCH_SIZE = 32
LEARNING_RATE = 0.0005
NUM_EPOCHS = 30
WEIGHT_DECAY = 0.005
TRAIN_DATA_PATH = "C:/AD_NC/train"
TEST_DATA_PATH = "C:/AD_NC/test"
MODEL_SAVE_PATH = "model/GFNet"
DROPOUT_RATE = 0.3
SCHEDULER_FACTOR = 0.5
SCHEDULER_PATIENCE = 1
