name: torch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.4
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.0
  - zlib=1.2.13
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.53.1
      - fsspec==2024.2.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nibabel==5.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - pandas==2.2.2
      - pillow==10.2.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - triton==3.0.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
