#!/bin/bash
#SBATCH --time=00:00:00
#SBATCH --partition=p100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:p100
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s4708525@student.uq.edu.au
#SBATCH --job-name=conv-VIT
#SBATCH -o output/trial_code3_100epochs_p100.out

conda activate torch
python trial_code3_5epochs.py
