#!/bin/bash
#SBATCH --time=6:00:00
#SBATCH --partition=comp3710 
#SBATCH --account=comp3710
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s4708525@student.uq.edu.au
#SBATCH --job-name=coVIT
#SBATCH -o output/trial_code3_100epochs_com3710.out

conda activate torch
python trial_code3_5epochs.py
